// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guests.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGuest = `-- name: CreateGuest :one
INSERT INTO guests(ID, RsvpID, Name, IsChild)
VALUES($1, $2, $3, $4)
RETURNING id, rsvpid, name, ischild
`

type CreateGuestParams struct {
	ID      pgtype.UUID
	Rsvpid  pgtype.UUID
	Name    string
	Ischild bool
}

func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error) {
	row := q.db.QueryRow(ctx, createGuest,
		arg.ID,
		arg.Rsvpid,
		arg.Name,
		arg.Ischild,
	)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.Rsvpid,
		&i.Name,
		&i.Ischild,
	)
	return i, err
}

const getGuests = `-- name: GetGuests :many
SELECT id, rsvpid, name, ischild
FROM guests
ORDER BY RsvpID, Name
`

func (q *Queries) GetGuests(ctx context.Context) ([]Guest, error) {
	rows, err := q.db.Query(ctx, getGuests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guest
	for rows.Next() {
		var i Guest
		if err := rows.Scan(
			&i.ID,
			&i.Rsvpid,
			&i.Name,
			&i.Ischild,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
