// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Guest struct {
	ID      pgtype.UUID
	Rsvpid  pgtype.UUID
	Name    string
	Ischild bool
	Drinker bool
}

type Rsvp struct {
	ID        pgtype.UUID
	Createdat pgtype.Timestamp
	Name      string
	Email     string
	Attending bool
	Allergies pgtype.Text
	Drinker   bool
	Question  pgtype.Text
}
