// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rsvps.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRsvp = `-- name: CreateRsvp :one
INSERT INTO rsvps(ID, CreatedAt, Name, Email, Attending, Allergies, Drinker, Question) 
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, createdat, name, email, attending, allergies, drinker, question
`

type CreateRsvpParams struct {
	ID        pgtype.UUID
	Createdat pgtype.Timestamp
	Name      string
	Email     string
	Attending bool
	Allergies pgtype.Text
	Drinker   bool
	Question  pgtype.Text
}

func (q *Queries) CreateRsvp(ctx context.Context, arg CreateRsvpParams) (Rsvp, error) {
	row := q.db.QueryRow(ctx, createRsvp,
		arg.ID,
		arg.Createdat,
		arg.Name,
		arg.Email,
		arg.Attending,
		arg.Allergies,
		arg.Drinker,
		arg.Question,
	)
	var i Rsvp
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Name,
		&i.Email,
		&i.Attending,
		&i.Allergies,
		&i.Drinker,
		&i.Question,
	)
	return i, err
}

const deleteRsvp = `-- name: DeleteRsvp :execrows
DELETE FROM rsvps
WHERE ID = $1
`

func (q *Queries) DeleteRsvp(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRsvp, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRsvpByEmail = `-- name: GetRsvpByEmail :one
SELECT Email
FROM rsvps
WHERE Email = $1
`

func (q *Queries) GetRsvpByEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, getRsvpByEmail, email)
	var email_2 string
	err := row.Scan(&email_2)
	return email_2, err
}

const getRsvps = `-- name: GetRsvps :many
SELECT id, createdat, name, email, attending, allergies, drinker, question
FROM rsvps
ORDER BY CreatedAt
`

func (q *Queries) GetRsvps(ctx context.Context) ([]Rsvp, error) {
	rows, err := q.db.Query(ctx, getRsvps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rsvp
	for rows.Next() {
		var i Rsvp
		if err := rows.Scan(
			&i.ID,
			&i.Createdat,
			&i.Name,
			&i.Email,
			&i.Attending,
			&i.Allergies,
			&i.Drinker,
			&i.Question,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
